version: '3.8'

services:
  webapp:
    container_name: runnersapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # environment:
    #   - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=runnersapp_db;Username=postgres;Password=postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - CloudinarySettings__CloudName=${CLOUDINARY_CLOUD_NAME}
      - CloudinarySettings__ApiKey=${CLOUDINARY_API_KEY}
      - CloudinarySettings__ApiSecret=${CLOUDINARY_API_SECRET}
      - IPInfoToken=${IPINFO_TOKEN}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: runnersapp_db
    environment:
      POSTGRES_DB: runnersapp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
