version: '3.8'

services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: RunGroop-dotnetMVC-bab
    ports:
      - "5222:5222"
    # env_file:
    #   - ./.env # Load environment variables
    environment:
      ASPNETCORE_ENVIRONMENT: development
      # DefaultConnection: Host=postgres;Database=FinShark;Username=postgres;Password=admin
      ASPNETCORE_URLS: http://+:5222

    depends_on:
      - postgres
    # restart: always

    volumes:
      - .:/app
      - ./keys:/root/.aspnet/DataProtection-Keys

  postgres:
    image: postgres:13 # Using the official PostgreSQL image
    container_name: RunGroop-postgres-bab
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=RunGroop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data

volumes:
  pgdata:
